name: CI/CD Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: |
          sudo apt update
          sudo apt install openssh-client -y

      - name: Set up SSH agent
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "${{ secrets.SSH_PRIVATE_KEY_DEVL }}" >> ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Install dependencies and build using npm
        run: "npm run deno-deploy"

      - name: Archive build artifacts
        run: |
          tar -czvf devl.intellectualfrontiers.tar.gz deno-deploy

      - name: Copy build artifacts to the development server
        run: |
          scp -p422 -o StrictHostKeyChecking=no devl.intellectualfrontiers.tar.gz "${{ secrets.DEVELOPMENT_DEPLOYMENT_USER }}@${{ secrets.DEVELOPMENT_DEPLOYMENT_SERVER_IP }}:"

      - name: Deploy to development server
        run: |
          ssh -p422 -o StrictHostKeyChecking=no -t ${{ secrets.DEVELOPMENT_DEPLOYMENT_USER }}@${{ secrets.DEVELOPMENT_DEPLOYMENT_SERVER_IP }} "bash -i devl-intellectual-frontiers.sh"
